import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const omori = localFont({
  src: './OMORI_GAME2.ttf',
  display: 'swap',
  variable: '--font-omori',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${omori.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
